from magicapi.Errors import MagicException


class TestError(MagicException):
    pass
